FROM node:10.16-alpine

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

# set working directory
WORKDIR /home/node/app

# install server packages
COPY package*.json ./
RUN npm set progress=false && npm install --production

# copy server files
COPY src src
<% if (sequelize) { %>COPY .sequelizerc .
<% } -%>

EXPOSE 8080

CMD [ "npm", "start" ]
